---
- assert:
    that: item.name

- assert:
    that: "'-' not in item.name"

- name: Install borg archive script
  become: yes
  template:
    src: templates/borg-backup.sh
    dest: "{{ borg_scripts_root }}/backup_{{ item.name }}.sh"
    mode: +x
